"""full auth system

Revision ID: 723ae0de6aad
Revises:
Create Date: 2026-04-20 13:36:13.027397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "723ae0de6aad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("auth_provider", sa.String(length=20), nullable=True)
    )
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("verify_token", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("verify_token_exp", sa.DateTime(), nullable=True))
    op.add_column(
        "users", sa.Column("reset_token", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("reset_token_exp", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("github_id", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("github_username", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    op.add_column("users", sa.Column("phone_otp", sa.String(length=6), nullable=True))
    op.add_column("users", sa.Column("phone_otp_exp", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("phone_otp_attempts", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("phone_otp_locked_until", sa.DateTime(), nullable=True)
    )
    op.add_column("users", sa.Column("phone_verified", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=100),
        nullable=True,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "users", ["phone_number"])
    op.create_unique_constraint(None, "users", ["google_id"])
    op.create_unique_constraint(None, "users", ["github_id"])
    op.drop_column("users", "github_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("github_token", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("users", "last_login")
    op.drop_column("users", "is_active")
    op.drop_column("users", "phone_verified")
    op.drop_column("users", "phone_otp_locked_until")
    op.drop_column("users", "phone_otp_attempts")
    op.drop_column("users", "phone_otp_exp")
    op.drop_column("users", "phone_otp")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "github_username")
    op.drop_column("users", "github_id")
    op.drop_column("users", "google_id")
    op.drop_column("users", "reset_token_exp")
    op.drop_column("users", "reset_token")
    op.drop_column("users", "verify_token_exp")
    op.drop_column("users", "verify_token")
    op.drop_column("users", "is_verified")
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
